var apiv1= {};

/* define api route and descriptions */

apiv1 = {};

apiv1.sites = {};

apiv1.sites.get_site_by_id = {
	id : "v1-get-site-by-id",
	action : "GET",
	url : "/api/v1/sites/",
	syntax : "/api/v1/sites/{id}/{year}/{month}/{day}",
	desc : "Retrieve info of a site if {id} is provided, otherwise, return all sites. [optional] {year}/{month}/{day} will limit the time range from which testsheets will be retrieved.",
	fields : [
		{
			name : "id",
			type : "int",
			desc : "A unique site id auto-generated by the database"
		},
		{
			name : "pin",
			type : "string",
			desc : "A supposedly unique PIN associated with the site. This is used to match the site in FFS's database with DHS's own."
		},
		{
			name : "type",
			type : "string"
		},
		{
			name : "type_id",
			type : "int"
		},
		{
			name : "address",
			type : "object",
			desc : "Site's full address",
			fields : [
				{
					name : "number",
					type : "string",
					desc : ""
				},
				{
					name : "street",
					type : "string",
					desc : ""
				},
				{
					name : "suburb",
					type : "object",
					desc : "",
					fields : [
						{
							name : "id",
							type : "int",
							desc : ""
						},
						{
							name : "name",
							type : "string",
							desc : ""
						}
					]
				}

			]
		},
		{
			name : "testsheets",
			type : "array",
			desc : "NOTE: This field is currently not in scope. <br/> All testsheets associated with this site by default. Can be limited by adding {year}/{month}/{day} to url",
			fields : [
				{
					name : "id",
					type : "int"
				},
				{
					name : "test_sheet_number",
					type : "int"
				},
				{
					name : "type",
					type : "object",
					fields : [
						{
							name : "id",
							type : "int"
						}
					]
				},
				{
					name : "interval",
					type : "array",
					desc : "All interval associated with this test sheet (a test sheet can have multiple interval)",
					fields : [
						{
							name : "id",
							type : "int"
						}
					]
				},
				{
					name : "note",
					type : "string",
					desc : "Hand-added note that are not included in any other standard field"
				},
				{
					name : "date",
					type : "timestamp",
					desc : "Date written on test sheet"
				},
				{
					name : "date_created",
					type : "timestamp",
					desc : "Date entered into database"
				},
				{
					name : "date_modified",
					type : "timestamp",
					desc : "Date last modified"
				},
				// {
				// 	name : "sites",
				// 	type : "array",
				// 	desc : "id's of all sites associated with this testsheet"
				// },
				{
					name : "scan_url",
					type : "string",
					desc : "Url to the scan image file"
				}
			]
		}
	]
};

apiv1.testsheets = {};

apiv1.testsheets.get_test_sheet_by_site_id = {
	id : "v1-get-test-sheet-by-site-id",
	action : "GET",
	url : "/api/v1/testsheets/?site={id}&year={year}&={month}",
	syntax : "/api/v1/testsheets/?site={id}",
	desc : "Retrieve all test sheets associated with the site with the provided id. Use query \"year\" and \"month\" to get testsheets int hat month only."
}


apiv1.testsheets.get_test_sheet_types = {
	id : "v1-get-test-sheet-types",
	action : "GET",
	url : "/api/v1/testsheets/types/",
	syntax : "/api/v1/testsheets/types/",
	desc : "Retrieve all test sheet types"
}





module.exports = apiv1;